language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
    
env:
  global:
    - CC_TEST_REPORTER_ID=833490a5d275e269aeafa9de0049fb7a5a96ff9ebfdbb76fb47d6bd990991838

before_install:
  - npm i -g npm@latest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install
  - npm install @rxstack/core@^0.4 @rxstack/exceptions@^0.4 @rxstack/platform@^0.4 @rxstack/query-filter@^0.4 @rxstack/security@^0.4 @rxstack/async-event-dispatcher@^0.4 @rxstack/service-registry@^0.4

script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT