# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm install
      - run: npm test
      - run: npm install --no-save @rxstack/core@^0.7 @rxstack/platform@^0.7 @rxstack/security@^0.7 @rxstack/query-filter@^0.6 @rxstack/exceptions@^0.6  @rxstack/async-event-dispatcher@^0.6 @rxstack/service-registry@^0.6 winston@^3.5
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 833490a5d275e269aeafa9de0049fb7a5a96ff9ebfdbb76fb47d6bd990991838
